# **Feature Engineering**
 Feature engineering the cleaned data for optimising the modeling of the data

In [9]:
import numpy as np
import pandas as pd

In [10]:
df=pd.read_csv('Titanic-Survival-Dataset/Data/processed/cleaned_data.csv')
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S
0,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,7.2500,False,True
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,71.2833,False,False
2,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,7.9250,False,True
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,53.1000,False,True
4,0,3,"Allen, Mr. William Henry",0,35.0,0,0,8.0500,False,True

In [11]:
df['FamilySize']=df['SibSp']+df['Parch']+1
df['IsAlone']=np.where(df['FamilySize']==1,1,0)
df['Title'] = df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

In [12]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S,FamilySize,IsAlone,Title
0,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,7.2500,False,True,2,0,Mr
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,71.2833,False,False,2,0,Mrs
2,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,7.9250,False,True,1,1,Miss
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,53.1000,False,True,2,0,Mrs
4,0,3,"Allen, Mr. William Henry",0,35.0,0,0,8.0500,False,True,1,1,Mr

In [13]:
df['Title'] = df['Title'].map({'Mr':0, 'Miss':1, 'Mrs':2, 'Master':3, 'Rare':4})

In [14]:
df['AgeBand'] = pd.cut(df['Age'], bins=[0,12,20,40,60,80], labels=[0,1,2,3,4])
df=df.drop(['Name'], axis=1)

In [15]:
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_Q,Embarked_S,FamilySize,IsAlone,Title,AgeBand
0,0,3,0,22.0,1,0,7.2500,False,True,2,0,0.0,2
1,1,1,1,38.0,1,0,71.2833,False,False,2,0,2.0,2
2,1,3,1,26.0,0,0,7.9250,False,True,1,1,1.0,2
3,1,1,1,35.0,1,0,53.1000,False,True,2,0,2.0,2
4,0,3,0,35.0,0,0,8.0500,False,True,1,1,0.0,2

In [16]:
df.to_csv('Titanic-Survival-Dataset/Data/processed/feature_engineered_data.csv', index=False)