# Model Analysis

In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [19]:
df=pd.read_csv('Walmart-Sales-Dataset/Data/processed/cleaned_data.csv')
df.head()

   Unnamed: 0  Store  Dept        Date  ...  Unemployment  Year Month  Week
0           0      1     1  2010-02-05  ...         8.106  2010     2     5
1           1      1     1  2010-02-12  ...         8.106  2010     2     6
2           2      1     1  2010-02-19  ...         8.106  2010     2     7
3           3      1     1  2010-02-26  ...         8.106  2010     2     8
4           4      1     1  2010-03-05  ...         8.106  2010     3     9

[5 rows x 20 columns]

In [20]:

df['Weekly_Sales']=df['Weekly_Sales'].fillna(df['Weekly_Sales'].median())
df.head()

   Unnamed: 0  Store  Dept        Date  ...  Unemployment  Year Month  Week
0           0      1     1  2010-02-05  ...         8.106  2010     2     5
1           1      1     1  2010-02-12  ...         8.106  2010     2     6
2           2      1     1  2010-02-19  ...         8.106  2010     2     7
3           3      1     1  2010-02-26  ...         8.106  2010     2     8
4           4      1     1  2010-03-05  ...         8.106  2010     3     9

[5 rows x 20 columns]

In [21]:
df['Weekly_Sales']=np.log1p(df['Weekly_Sales'])

c:\Dev\Projects\EDA-Portfolio\venv\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: invalid value encountered in log1p
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [23]:
df.dropna(subset=['Weekly_Sales'],inplace=True)
df.isnull().sum().sort_values(ascending=False)

Unnamed: 0      0
Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
Type            0
Size            0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
Year            0
Month           0
Week            0
dtype: int64

In [24]:
x=df.drop(['Weekly_Sales'],axis=1)
y=df['Weekly_Sales']
x=pd.get_dummies(x,drop_first=True)
x.head()

   Unnamed: 0  Store  Dept  ...  Date_2012-10-26  Type_B  Type_C
0           0      1     1  ...            False   False   False
1           1      1     1  ...            False   False   False
2           2      1     1  ...            False   False   False
3           3      1     1  ...            False   False   False
4           4      1     1  ...            False   False   False

[5 rows x 161 columns]